  -- BeautyDrops — schema database
-- Eseguire su PostgreSQL per creare le tabelle necessarie.
-- Lo script è idempotente: può essere rieseguito senza distruggere i dati esistenti.

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(30) NOT NULL CHECK (category IN ('cosmetici', 'elettronica', 'abbigliamento')),
  brand VARCHAR(100) NOT NULL,
  name VARCHAR(150) NOT NULL,
  variants JSONB NULL,
  image_path VARCHAR(255),
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  orderable_quantity INTEGER NOT NULL DEFAULT 0,
  price NUMERIC(10,2) NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Aggiunta in una revisione successiva: CREATE TABLE IF NOT EXISTS non tocca
-- le tabelle già esistenti, quindi serve un ALTER esplicito e idempotente
-- per chi ha già eseguito lo schema prima di questa colonna.
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type VARCHAR(40) NULL;

CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_brand ON products (brand);
CREATE INDEX IF NOT EXISTS idx_products_type ON products (product_type);

-- Aggiorna automaticamente updated_at ad ogni UPDATE su products.
CREATE OR REPLACE FUNCTION set_products_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION set_products_updated_at();

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(150) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS offers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  offer_price NUMERIC(10,2) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS offer_products (
  offer_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  PRIMARY KEY (offer_id, product_id),
  FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_token VARCHAR(64) NOT NULL,
  customer_first_name VARCHAR(100) NOT NULL,
  customer_last_name VARCHAR(100) NOT NULL,
  customer_email VARCHAR(150) NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(10,2) NOT NULL DEFAULT 0,
  total NUMERIC(10,2) NOT NULL DEFAULT 0,
  has_price_on_request BOOLEAN NOT NULL DEFAULT FALSE,
  pdf_path VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT idx_orders_token UNIQUE (access_token)
);

CREATE TABLE IF NOT EXISTS product_gallery_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_gallery_images_product ON product_gallery_images (product_id);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL,
  product_id INTEGER NULL,
  brand VARCHAR(100) NOT NULL,
  name VARCHAR(150) NOT NULL,
  variant VARCHAR(150) NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10,2) NULL,
  discount_percent INTEGER NOT NULL DEFAULT 0,
  line_total NUMERIC(10,2) NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

-- Nessun admin di default: creare/aggiornare l'account amministratore con
-- `php scripts/create-admin.php` impostando le variabili d'ambiente
-- ADMIN_EMAIL e ADMIN_PASSWORD prima di eseguirlo.
